"""Benford's Law test for detecting fabricated large-scale datasets.

Naturally occurring numerical data spanning multiple orders of magnitude
follow Benford's Law: P(first digit = d) = log10(1 + 1/d).

If a dataset was generated by Excel RAND() or hand-typed, the first-digit
distribution tends toward uniformity (~11% each), not Benford's Law
(~30% for 1, ~5% for 9).

IMPORTANT: Only applies to raw, untransformed data (counts, concentrations,
demographics). NOT applicable to log-transformed, Z-score normalized,
or TPM/RPKM data — these transformations inherently distort digit distribution.

Supports two data sources:
  1. --data-file CSV  → reads CSV, runs Benford per numeric column
  2. PDF text         → extracts numbers from full_text (fallback, noisy)
"""

from __future__ import annotations

import csv
import math
import re
from collections import Counter
from pathlib import Path

import numpy as np
from scipy import stats as scipy_stats

from paperfraud.base import CheckResult


BENFORD_EXPECTED = np.array([math.log10(1 + 1 / d) for d in range(1, 10)])


def _extract_first_digits(values: list[float]) -> list[int]:
    """Extract first significant digits from a list of numeric values.

    Filters: values < 1 (no well-defined first digit), zeros.
    """
    digits = []
    for v in values:
        if v < 1 or not np.isfinite(v):
            continue
        first = int(str(int(abs(v)))[0])
        if 1 <= first <= 9:
            digits.append(first)
    return digits


def _read_csv_columns(file_path: str) -> dict[str, list[float]]:
    """Read a CSV/TSV file and extract numeric columns.

    Returns {column_name: [values]} for columns with at least some numeric data.
    Handles tab-separated and comma-separated files.
    """
    path = Path(file_path)
    if not path.exists():
        return {}

    # Detect delimiter
    with open(path, encoding="utf-8-sig") as f:
        sample = f.read(4096)
    delimiter = "\t" if sample.count("\t") > sample.count(",") else ","

    columns: dict[str, list[float]] = {}
    with open(path, encoding="utf-8-sig") as f:
        reader = csv.DictReader(f, delimiter=delimiter)
        for row in reader:
            for key, val in row.items():
                key = key.strip()
                if key not in columns:
                    columns[key] = []
                try:
                    columns[key].append(float(val.strip()))
                except (ValueError, TypeError):
                    columns[key].append(float("nan"))

    # Keep only columns with >= 10 numeric non-NaN values
    return {
        k: [v for v in vals if not np.isnan(v)]
        for k, vals in columns.items()
        if sum(1 for v in vals if not np.isnan(v)) >= 10
    }


def _check_benford(first_digits: list[int], label: str = "") -> dict:
    """Run chi-squared test comparing observed vs Benford expected distribution."""
    n = len(first_digits)
    if n < 50:
        return {
            "label": label,
            "n": n,
            "observed": Counter(first_digits),
            "expected_pct": None,
            "chi2": None,
            "p_value": None,
            "is_suspicious": False,
            "note": f"样本量不足 (n={n}，需 ≥ 50)",
        }

    observed_counts = Counter(first_digits)
    observed_arr = np.array([observed_counts.get(d, 0) for d in range(1, 10)])
    expected_arr = BENFORD_EXPECTED * n

    if np.any(expected_arr < 5):
        return {
            "label": label,
            "n": n,
            "observed": observed_counts,
            "expected_pct": None,
            "chi2": None,
            "p_value": None,
            "is_suspicious": False,
            "note": f"期望频数不足，无法执行卡方检验",
        }

    chi2, p_value = scipy_stats.chisquare(observed_arr, f_exp=expected_arr)
    observed_pcts = observed_arr / n
    max_deviation = float(np.max(np.abs(observed_pcts - BENFORD_EXPECTED)))
    is_suspicious = bool(p_value < 0.01)

    return {
        "label": label,
        "n": n,
        "observed": observed_counts,
        "observed_pct": {d: round(observed_counts.get(d, 0) / n * 100, 1) for d in range(1, 10)},
        "expected_pct": {d: round(BENFORD_EXPECTED[i] * 100, 1) for i, d in enumerate(range(1, 10))},
        "chi2": float(chi2),
        "p_value": float(p_value),
        "max_deviation": max_deviation,
        "is_suspicious": is_suspicious,
    }


def _extract_first_digits_from_text(text: str) -> list[int]:
    """Fallback: extract first digits from PDF text (noisy).

    Filters out common metadata patterns:
      - Years, DOIs, multi-dot numbers
      - P-values, test statistics (n=, t=, F=, r=, χ²=)
      - Figure/table references, bracketed citations
      - Section numbers, page numbers
    """
    pattern = re.compile(r'(?<!\d)(\d+\.?\d*)(?!\d)')
    digits = []

    for match in pattern.finditer(text):
        val_str = match.group(0)

        # --- Hard numeric filters ---
        if re.match(r'^(19|20)\d{2}$', val_str):
            continue
        if re.match(r'^\d+\.\d+(?:\.\d+)+$', val_str):
            continue
        if re.match(r'^10\.\d{4,}', val_str):
            continue

        # --- Context-based filters ---
        start = max(0, match.start() - 30)
        end = min(len(text), match.end() + 30)
        ctx = text[start:end]

        if _is_metadata_context(ctx, match.group(0)):
            continue

        try:
            val = float(val_str)
        except ValueError:
            continue
        if val < 1:
            continue
        first = int(str(int(abs(val)))[0])
        if 1 <= first <= 9:
            digits.append(first)
    return digits


# Metadata patterns for context filtering
_METADATA_PATTERNS = [
    # P-values: "P < 0.05", "P > 0.05", "P = 0.032", "p ≤ 0.01"
    re.compile(r'[Pp]\s*[<>=≤≥]\s*\d'),
    # Test statistics: "t = 2.34", "F = 5.67", "r = 0.89", "χ² = 12.3", "z = 1.96"
    re.compile(r'\b[tFrRzZχ]\s*[=≈]\s*\d'),
    # Sample size: "n = 6", "N = 100"
    re.compile(r'\b[nN]\s*=\s*\d'),
    # Figure/table references: "Figure 1", "Fig. 2", "Table 3"
    re.compile(r'(?:Figure|Fig\.?|Table)\s*\d', re.IGNORECASE),
    # Bracketed citations: "[1]", "[23,45]", "[1-5]", "[1, 2]"
    re.compile(r'\[\d+(?:\s*[,.\-–—]\s*\d+)*\]'),
    # Parenthesized citations: "(1, 2)", "(1–3)", "(4–11)", "(12– 15)"
    re.compile(r'\(\d+(?:\s*[,.\-–—]\s*\d+)*\)'),
    # DOI in nearby text: "doi:10.xxx", "doi.org/10.xxx"
    re.compile(r'(?:doi|DOI)\s*[:.]?\s*10\.\d', re.IGNORECASE),
    # Year ranges: "2020-2024", "2019–2023"
    re.compile(r'(?:19|20)\d{2}\s*[-–—]\s*(?:19|20)\d{2}'),
    # Months with years: "March 2025", "January 2024"
    re.compile(r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+(?:19|20)\d{2}', re.IGNORECASE),
    # Section numbers at line starts: "2.1 Cells and virus", "3.2 Results"
    re.compile(r'(?:^|\n)\s*\d+\.\d+(?:\.\d+)?\s+[A-Z]'),
    # CI notation: "95% CI: 0.5-1.2", "CI 0.3 to 0.8"
    re.compile(r'(?:95%?\s*)?CI\s*[=:]\s*\d', re.IGNORECASE),
    # Page-like numbers: "Page 5", "p. 123"
    re.compile(r'(?:[Pp]age|[Pp]\.)\s*\d+'),
    # Volume/issue: "Volume 16 Issue 3"
    re.compile(r'(?:Volume|Issue)\s+\d+', re.IGNORECASE),
    # Date fragments: "Accepted 13 March 2026", "Published 25 April 2022"
    re.compile(r'(?:Accepted|Published|Received)\s+\d+\s+(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+(?:19|20)\d{2}', re.IGNORECASE),
    # Author affiliation superscripts: "Das,1", "Banerjee,2,3,4,5,6"
    re.compile(r'(?:^|\s|,)\d+(?:,\d+){2,}'),  # "2,3,4,5,6" style sequences
    re.compile(r'[a-z],\d+(?:,\d+)*\b'),  # "Das,1" or "Tizon,2,3" style
    # Gene/protein/virus names with embedded numbers: "SARS-CoV-2", "IL-1β", "caspase-1"
    re.compile(r'[A-Za-z]{2,}[-–—]\d+\b'),
    # Email/URL fragments with numbers
    re.compile(r'@\S+\.\d+'),
    # Grant numbers: "Grant No. 32402964"
    re.compile(r'(?:Grant|Project)\s+(?:No\.?|Number)\s+\d+', re.IGNORECASE),
]


def _is_metadata_context(ctx: str, matched_num: str) -> bool:
    """Check if a number's surrounding context indicates it's metadata, not data."""
    for pat in _METADATA_PATTERNS:
        if pat.search(ctx):
            return True
    return False


def _format_evidence(result: dict) -> list[str]:
    """Build human-readable evidence from a Benford result."""
    evidence = []
    obs = result.get("observed_pct")
    exp = result.get("expected_pct")
    if obs and exp:
        for d in range(1, 10):
            o = obs.get(d, 0)
            e = exp.get(d, 0)
            bar = "█" * max(1, int(o / 2))
            evidence.append(f"首位数 {d}: 实测 {o:5.1f}% 预期 {e:4.1f}% {bar}")
    if result.get("chi2") is not None:
        evidence.append(f"χ²={result['chi2']:.2f}, P={result['p_value']:.4f}")
    return evidence


def run_benford(paper) -> list[CheckResult]:
    """Run Benford's Law test.

    If paper.data_file is set, reads CSV and tests each numeric column.
    Otherwise falls back to extracting numbers from PDF full_text (noisy).
    """
    MAX_TEXT = 500_000

    # --- CSV mode (preferred) ---
    if paper.data_file:
        columns = _read_csv_columns(paper.data_file)
        if not columns:
            return [
                CheckResult(
                    check_id="numbers.benford",
                    check_name="本福特定律",
                    level="error",
                    verdict=f"无法解析数据文件: {paper.data_file}",
                    needs_human=False,
                )
            ]

        all_results = []
        for col_name, values in columns.items():
            digits = _extract_first_digits(values)
            result = _check_benford(digits, label=col_name)
            all_results.append(result)

        suspicious = [r for r in all_results if r["is_suspicious"]]
        passed = [r for r in all_results if not r["is_suspicious"] and r["chi2"] is not None]
        skipped = [r for r in all_results if r["chi2"] is None]
        total_cols = len(all_results)

        evidence = []
        for r in suspicious:
            evidence.append(f"[{r['label']}] n={r['n']}, χ² P={r['p_value']:.4f} — 偏离本福特")
            evidence.extend(f"  {e}" for e in _format_evidence(r)[:3])

        if suspicious:
            return [
                CheckResult(
                    check_id="numbers.benford",
                    check_name="本福特定律",
                    level="orange",
                    verdict=f"{len(suspicious)}/{total_cols} 列偏离本福特定律（来自 {Path(paper.data_file).name}）",
                    evidence=evidence[:15],
                    confidence=0.85,
                    needs_human=True,
                    human_instruction="检查数据是否经过 Log2/Z-score/TPM 等标准化处理。"
                    "若为转换后数据，本福特检验不适用，可降级为绿灯。"
                    "核对论文 Methods 章节中的数据处理说明。",
                )
            ]

        evidence = [f"共检测 {total_cols} 列数值（{Path(paper.data_file).name}）"]
        for r in passed:
            evidence.append(f"[{r['label']}] n={r['n']}, χ² P={r['p_value']:.3f} — 符合本福特")
        for r in skipped:
            evidence.append(f"[{r['label']}] {r.get('note', '跳过')}")

        return [
            CheckResult(
                check_id="numbers.benford",
                check_name="本福特定律",
                level="green",
                verdict=f"全部 {len(passed)} 列符合本福特定律（{len(skipped)} 列跳过）",
                evidence=evidence[:15],
                confidence=0.85,
                needs_human=False,
            )
        ]

    # --- PDF text fallback ---
    # Prefer Results section (highest data/metadata ratio)
    # Fall back to abstract + results, then full_text
    text = paper.results or ""
    if len(text) < 500 and paper.abstract:
        text = paper.abstract + "\n" + paper.results
    if len(text) < 500:
        text = paper.full_text
    text_truncated = len(text) > MAX_TEXT
    if text_truncated:
        text = text[:MAX_TEXT]

    if not text:
        return [
            CheckResult(
                check_id="numbers.benford",
                check_name="本福特定律",
                level="error",
                verdict="无法执行：未提取到文本，且未提供 --data-file",
                needs_human=False,
            )
        ]

    digits = _extract_first_digits_from_text(text)

    if len(digits) < 50:
        return [
            CheckResult(
                check_id="numbers.benford",
                check_name="本福特定律",
                level="green",
                verdict=f"有效数值不足（n={len(digits)}，需 ≥ 50）。建议使用 --data-file 传入 CSV 数据获得更准确结果。",
                evidence=[f"从 PDF 文本中仅提取到 {len(digits)} 个 ≥1 的数值"],
                needs_human=False,
            )
        ]

    result = _check_benford(digits, label="PDF全文")
    evidence = _format_evidence(result)
    if text_truncated:
        evidence.insert(0, "⚠️ 输入文本超过 500K 字符，仅检测前 500K")

    if result["is_suspicious"]:
        return [
            CheckResult(
                check_id="numbers.benford",
                check_name="本福特定律",
                level="yellow",
                verdict=f"首位数分布偏离本福特定律（n={result['n']}, χ² P={result['p_value']:.4f}；"
                f"注意：PDF 文本提取含噪声，建议用 --data-file 传入原始数据复验）"
                + ("（文本已截断）" if text_truncated else ""),
                evidence=evidence[:13],
                confidence=0.35,
                needs_human=True,
                human_instruction="PDF 文本提取的数值含噪声（P值、坐标轴标签混入），结果仅供参考。"
                "建议用 --data-file 传入 Supplementary CSV/Excel 原始数据复验。",
            )
        ]

    return [
        CheckResult(
            check_id="numbers.benford",
            check_name="本福特定律",
            level="green",
            verdict=f"首位数分布符合本福特定律（n={result['n']}, χ² P={result['p_value']:.3f}）"
            + ("（文本已截断）" if text_truncated else ""),
            evidence=evidence[:13],
            confidence=0.35,  # Low confidence: PDF text extraction is inherently noisy
            needs_human=False,
        )
    ]
